#pragma once

enum class [[nodiscard]] CardImage
{
    RedHerb,
    GreenHerb,
    MixedHerbs,
    FirstAid,
    Ammo,
    PistolParts,
    SilencedPistol,
    Pistol,
    Shotgun,
    Crossbow,
    RocketLauncher,
    Crate,
    Vaccine,
    YellowJewel,
    YellowJewelBox,
    RedJewel,
    RedJewelBox,
    Zombie,
    CrimsonHead,
    Licker,
    Cerberus,
    Hunter,
    Tyrant,
    MoonCrestLeft,
    MoonCrestRight,
    MoonCrest,
    SunCrest,
    CrestDoorEmpty,
    CrestDoorWithOneCrest,
    ShieldKey,
    ShieldDoor,
    DiamondKey,
    DiamondDoor,
    WeaponLockerKey,
    LockedWeaponLocker,
    WeaponLocker,

    Max
};
