#include "game/builders/CardBuilder.hpp"

const std::map<CardType, Card> CARD_DEFS = {
    // Weapons
    { CardType::Pistol,
      Card { .image = CardImage::Pistol,
             .traits = CardTrait::Pickable | CardTrait::Weapon,
             .quantity = 3,
             .power = 1,
             .name = "pistol",
             .text1 = "it uses 9mm ammo",
             .text2 = "standard police",
             .text3 = "firearm" } },
    { CardType::Shotgun,
      Card { .image = CardImage::Shotgun,
             .traits = CardTrait::Pickable | CardTrait::Weapon,
             .quantity = 2,
             .power = 2,
             .name = "shotgun",
             .text1 = "remington m1100" } },
    { CardType::Ammo,
      Card { .image = CardImage::Ammo,
             .traits = CardTrait::Pickable,
             .quantity = 3,
             .power = 0,
             .name = "ammo",
             .text1 = "restores ammo",
             .text2 = "for a chosen",
             .text3 = "weapon." } },

    // Healing
    { CardType::GreenHerb,
      Card { .image = CardImage::GreenHerb,
             .traits = CardTrait::Pickable,
             .quantity = 0,
             .power = 1,
             .name = "green herb",
             .text1 = "restores portion",
             .text2 = "of your health.",
             .text3 = "try mixing with",
             .text4 = "red herb." } },
    { CardType::RedHerb,
      Card { .image = CardImage::RedHerb,
             .traits = CardTrait::Pickable,
             .quantity = 0,
             .power = 0,
             .name = "red herb",
             .text1 = "mix with green",
             .text2 = "herb to improve",
             .text3 = "healing effect." } },
    { CardType::MixedHerbs,
      Card { .image = CardImage::MixedHerbs,
             .traits = CardTrait::Pickable,
             .quantity = 0,
             .power = 0,
             .name = "mixed herbs",
             .text1 = "restores to full",
             .text2 = "health." } },
    { CardType::FirstAid,
      Card { .image = CardImage::FirstAid,
             .traits = CardTrait::Pickable,
             .quantity = 0,
             .power = 3,
             .name = "first-aid spray",
             .text1 = "restores to full",
             .text2 = "health." } },

    // Items
    { CardType::Door,
      Card { .image = CardImage::Door,
             .quantity = 0,
             .power = 0,
             .name = "door",
             .text1 = "there's a shield",
             .text2 = "engraving above",
             .text3 = "the keyhole." } },
    { CardType::Key,
      Card { .image = CardImage::Key,
             .traits = CardTrait::Pickable,
             .quantity = 0,
             .power = 0,
             .name = "spade key",
             .text1 = "key with a",
             .text2 = "spade symbol." } },

    // Enemies
    { CardType::Zombie,
      Card { .image = CardImage::Zombie,
             .traits = CardTrait::Enemy,
             .quantity = 0,
             .power = 1,
             .name = "zombie",
             .text1 = "a former human",
             .text2 = "now crawing for",
             .text3 = "your flesh." } },
    { CardType::Licker,
      Card { .image = CardImage::Licker,
             .traits = CardTrait::Enemy,
             .quantity = 0,
             .power = 2,
             .name = "licker",
             .text1 = "mutated beast.",
             .text2 = "brain is exposed",
             .text3 = "and it has a",
             .text4 = "long tongue." } },
};

Card CardBuilder::createCard(CardType type)
{
    return CARD_DEFS.at(type);
}
