#include "game/builders/CardBuilder.hpp"

const std::map<CardType, Card> CARD_DEFS = {
    { CardType::Empty, Card { .image = CardImage::Max, .name = "--empty--" } },
    // Weapons
    { CardType::Pistol,
      Card { .image = CardImage::Pistol,
             .traits = CardTrait::Pickable | CardTrait::Weapon,
             .quantity = 3,
             .power = 1,
             .name = "pistol",
             .text1 = "it uses 9mm ammo",
             .text2 = "standard police",
             .text3 = "firearm" } },
    { CardType::Shotgun,
      Card { .image = CardImage::Shotgun,
             .traits = CardTrait::Pickable | CardTrait::Weapon,
             .quantity = 2,
             .power = 2,
             .name = "shotgun",
             .text1 = "remington m1100" } },
    { CardType::Shotgun,
      Card { .image = CardImage::RocketLauncher,
             .traits = CardTrait::Pickable | CardTrait::Weapon,
             .quantity = 1,
             .power = 3,
             .name = "rocket launcher",
             .text1 = "---" } },
    { CardType::Ammo,
      Card { .image = CardImage::Ammo,
             .traits = CardTrait::Pickable | CardTrait::Ammo,
             .quantity = 3,
             .power = 0,
             .name = "ammo",
             .text1 = "restores ammo",
             .text2 = "for a chosen",
             .text3 = "weapon." } },

    // Healing
    { CardType::GreenHerb,
      Card { .image = CardImage::GreenHerb,
             .traits = CardTrait::Pickable | CardTrait::Healing,
             .quantity = 0,
             .power = 3,
             .name = "green herb",
             .text1 = "restores portion",
             .text2 = "of your health.",
             .text3 = "try mixing with",
             .text4 = "red herb." } },
    { CardType::RedHerb,
      Card { .image = CardImage::RedHerb,
             .traits = CardTrait::Pickable | CardTrait::Healing,
             .quantity = 0,
             .power = 1,
             .name = "red herb",
             .text1 = "mix with green",
             .text2 = "herb to improve",
             .text3 = "healing effect." } },
    { CardType::MixedHerbs,
      Card { .image = CardImage::MixedHerbs,
             .traits = CardTrait::Pickable | CardTrait::Healing,
             .quantity = 0,
             .power = 5,
             .name = "mixed herbs",
             .text1 = "restores to full",
             .text2 = "health." } },
    { CardType::FirstAid,
      Card { .image = CardImage::FirstAid,
             .traits = CardTrait::Pickable | CardTrait::Healing,
             .quantity = 0,
             .power = 5,
             .name = "first-aid spray",
             .text1 = "restores to full",
             .text2 = "health." } },

    // Items
    { CardType::ShieldDoor,
      Card { .image = CardImage::ShieldDoor,
             .traits = CardTrait::KeyTarget1,
             .quantity = 0,
             .power = 0,
             .name = "door",
             .text1 = "there's a shield",
             .text2 = "engraving above",
             .text3 = "the keyhole." } },
    { CardType::ShieldKey,
      Card { .image = CardImage::ShieldKey,
             .traits = CardTrait::Pickable | CardTrait::KeyItem1,
             .quantity = 0,
             .power = 0,
             .name = "spade key",
             .text1 = "key with a",
             .text2 = "spade symbol." } },
    { CardType::MoonCrestLeft,
      Card { .image = CardImage::MoonCrestLeft,
             .traits = CardTrait::Pickable,
             .quantity = 0,
             .power = 0,
             .name = "moon crest (l)",
             .text1 = "combine with the",
             .text2 = "other half." } },
    { CardType::MoonCrestRight,
      Card { .image = CardImage::MoonCrestRight,
             .traits = CardTrait::Pickable,
             .quantity = 0,
             .power = 0,
             .name = "moon crest (r)",
             .text1 = "combine with the",
             .text2 = "other half." } },
    { CardType::MoonCrest,
      Card { .image = CardImage::MoonCrest,
             .traits = CardTrait::KeyItem2,
             .quantity = 0,
             .power = 0,
             .name = "moon crest",
             .text1 = "hexagonal crest",
             .text2 = "with an image of",
             .text3 = "a half moon." } },
    { CardType::MoonCrestDoor,
      Card { .image = CardImage::MoonCrestDoor,
             .traits = CardTrait::KeyTarget2,
             .quantity = 0,
             .power = 0,
             .name = "moon-crest door",
             .text1 = "there is a slot",
             .text2 = "for something of",
             .text3 = "hexagonal shape." } },

    // Enemies
    { CardType::Zombie,
      Card { .image = CardImage::Zombie,
             .traits = CardTrait::Enemy,
             .quantity = 0,
             .power = 1,
             .name = "zombie",
             .text1 = "on killed: 25%",
             .text2 = "to spawn a",
             .text3 = "crimson head." } },
    { CardType::CrimsonHead,
      Card { .image = CardImage::Max,
             .traits = CardTrait::Enemy,
             .quantity = 0,
             .power = 1,
             .name = "crimson head",
             .text1 = "first strike" } },
    { CardType::Licker,
      Card { .image = CardImage::Licker,
             .traits = CardTrait::Enemy,
             .quantity = 0,
             .power = 2,
             .name = "licker",
             .text1 = "mutated beast.",
             .text2 = "brain is exposed",
             .text3 = "and it has a",
             .text4 = "long tongue." } },
    { CardType::Cerberus,
      Card { .image = CardImage::Cerberus,
             .traits = CardTrait::Enemy,
             .quantity = 0,
             .power = 1,
             .name = "cerberus",
             .text1 = "first strike" } },

    // Misc
    { CardType::Crate,
      Card { .image = CardImage::Crate,
             .quantity = 0,
             .power = 0,
             .name = "crate",
             .text1 = "---" } },
    { CardType::BookCase,
      Card { .image = CardImage::Max,
             .quantity = 0,
             .power = 0,
             .name = "bookcase",
             .text1 = "books on various",
             .text2 = "subjects." } },
};

Card CardBuilder::createCard(CardType type)
{
    return CARD_DEFS.at(type);
}
